### ISSUE TITLE
Erro na porta

### ISSUE THREAD

**Issue by YujiYashima** [Rvkash/Foodfy-refact#2]
Eu rodei a aplicação e ela entra diretamente em `http://localhost:3000/` e só fica carregando. E quando eu coloco `http://localhost:5500/` como você sugeriu, aparece que nao foi possivel acessar o site. Pode ser conflito com as portas?

**Comment by Rvkash** [comment]
Na verdade é :5001 a porta, erro meu

**Comment by Rvkash** [comment]
Eu tinha alterado a porta no projeto, tá normal agora
